'use strict';

var decisions = {
	'start'  : 'Start',
	'v3b13'  : 'Service Available',
	'v3b12'  : 'Known method?',
	'v3b11'  : 'URI too long?',
	'v3b10'  : 'Method allowed?',
	'v3b9'   : 'Content-MD5 present?',
	'v3b9a'  : 'Content-MD5 valid?',
	'v3b9b'  : 'Malformed?',
	'v3b8'   : 'Authorized?',
	'v3b7'   : 'Forbidden?',
	'v3b6'   : 'Okay Content-* Headers?',
	'v3b5'   : 'Known Content-Type?',
	'v3b4'   : 'Req Entity Too Large?',
	'v3b3'   : 'OPTIONS?',
	'v3c3'   : 'Accept exists?',
	'v3c4'   : 'Acceptable media type available?',
	'v3d4'   : 'Accept-Language exists?',
	'v3d5'   : 'Acceptable Language available? %% WMACH-46',
	'v3e5'   : 'Accept-Charset exists?',
	'v3e6'   : 'Acceptable Charset available?',
	'v3f6'   : 'Accept-Encoding exists?',
	'v3f7'   : 'Acceptable encoding available?',
	'v3g7'   : 'Resource exists?',
	'v3g8'   : 'If-Match exists?',
	'v3g9'   : 'If-Match: * exists',
	'v3g11'  : 'ETag in If-Match',
	'v3h7'   : 'If-Match exists',
	'v3h10'  : 'If-unmodified-since exists?',
	'v3h11'  : 'I-UM-S is valid date?',
	'v3h12'  : 'Last-Modified > I-UM-S?',
	'v3i4'   : 'Moved permanently? (apply PUT to different URI)',
	'v3i7'   : 'PUT?',
	'v3i12'  : 'If-none-match exists?',
	'v3i13'  : 'If-None-Match: * exists?',
	'v3j18'  : 'GET or HEAD?',
	'v3k5'   : 'Moved permanently?',
	'v3k7'   : 'Previously existed?',
	'v3k13'  : 'Etag in if-none-match?',
	'v3l5'   : 'Moved temporarily?',
	'v3l7'   : 'POST?',
	'v3l13'  : 'IMS exists?',
	'v3l14'  : 'IMS is valid date?',
	'v3l15'  : 'IMS > Now?',
	'v3l17'  : 'Last-Modified > IMS?',
	'v3m5'   : 'POST?',
	'v3m7'   : 'Server allows POST to missing resource?',
	'v3m16'  : 'DELETE?',
	'v3m20'  : 'DELETE enacted immediately?',
	'v3n5'   : 'Server allows POST to missing resource?',
	'v3n11'  : 'Redirect?',
	'v3n16'  : 'POST?',
	'v3o14'  : 'Conflict?',
	'v3o16'  : 'PUT?',
	'v3o18'  : 'Multiple representations?',
	'v3o20'  : 'Response includes an entity?',
	'v3p3'   : 'Conflict?',
	'v3p11'  : 'New resource?',
	'finish' : 'Finish request'
};
module.exports.decisionTitles = decisions;
